apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-dalston
  namespace: dalston
  labels:
    type: local
spec:
  storageClassName: document
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db/dalston"